GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk


###
# Show the actual users
GET http://localhost:3000/users


###
#Add user to the list (Register)
POST http://localhost:3000/register
Content-Type: application/json

{
    "uname": "Julian",
    "psw": "password"
}

###
#Add second user to the list (Register)
POST http://localhost:3000/register
Content-Type: application/json

{
    "uname": "Mihael",
    "psw": "password"
}

###
#Login and create a jwt
POST http://localhost:3000/login
Content-Type: application/json

{
    "uname": "Julian",
    "psw": "password"
}
###
POST http://localhost:3000/list
Content-Type: application/json

[{
    "name":"List Name",
    "picture":"A Link"
}]

###
POST http://localhost:3000/list/AnimeList
Content-Type: application/json

[{
    "name":"TOODOO"
}]
###
POST http://localhost:3000/list/AnimeList/Done
Content-Type: application/json

[{
    "name": "A Title",
    "rating": "0/10",
    "description": "A Descripton",
    "deadline": "some date",
    "calendar": "yes"
}]

###
GET http://localhost:3000/weather/allWeather/Vienna

###
GET http://localhost:3000/weather/dayweather/Vienna

###
GET http://localhost:3000/weather/weatherandtemp/Vienna

###
GET http://localhost:3000/list/ESO Dungeons
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

###
GET http://localhost:3000/listIcons
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

###
PUT http://localhost:3000/list/ESO Dungeons
Content-Type: application/json

[{
    "name": "Test1",
    "picture": "Link",
    "weather":"Rain"
}]

###
GET http://localhost:3000/list/Electric Bungaloo/To-Do/New entry name1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

###
GET http://localhost:3000/list/Electric Bungaloo/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

###
PUT http://localhost:3000/list/ESO Dungeons/To-Do/Stuff
Content-Type: application/json

[{ 
    "name": "Corals", 
    "rating": "10 / 10", 
    "description": "Descripton", 
    "deadline": "30.03.2024", 
    "calendar": "yes"
}]

###
GET http://localhost:3000/weather/weatherandtemp/Vienna

###
GET http://localhost:3000/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

###
POST http://localhost:3000/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

[{
    "name":"Electric Bungaloo",
    "picture":"Link",
    "weather":"sunny"
}]

###
POST http://localhost:3000/list/New List
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSnVsaWFuIiwiaWF0IjoxNzE4NjA4Mzk2fQ.BdOM648Xnck8YTo1-V9kbkZ_6eaFZ2bXmzJ_J4OpBvk

[{
    "name":"New Cat"
}]

###
POST http://localhost:3000/list/New List/New Cat
Content-Type: application/json

[{ 
    "name": "Entry Name", 
    "rating": "10 / 10", 
    "description": "Descripton", 
    "deadline": "30.03.2024", 
    "calendar": "yes" 
}]

###
PUT http://localhost:3000/list/New List
Content-Type: application/json

[{ 
    "name": "New List", 
    "picture": "New Pic", 
    "wheater": "Rain" 
}]

###
GET  http://localhost:3000/Test

###
GET  http://localhost:3000/anime

###
GET  http://localhost:3000/manga